### ISSUE TITLE
Conflict with shortcodes from Easy Footnotes

### ISSUE THREAD

**Issue by patrickrobrecht** [pluginkollektiv/spcl#23] opened 2020-11-26 20:22 UTC
First reported in the [support forums](https://wordpress.org/support/topic/compatibility-glitches/). [Easy Footnotes](https://wordpress.org/plugins/easy-footnotes/) seems to be this plugin from the wp.org plugin directory.

> One of the sites I have this installed on also uses a footnote plugin that works by wrapping the footnote text in shortcodes. (Basically, it looks a bit like wrapping a link with HTML code when writing a webpage, but using shortcode syntax.) A lot of my links are in these footnotes, and the brackets seem to be confusing your plugin, so it’s not recognizing where a URL begins and ends. The footnote plugin is called Easy Footnotes.

**Comment by Zodiac1978** [comment] 2023-04-16 15:56
I couldn't reproduce this with the recent versions of SPCL, Easy Footnotes and WordPress. Maybe version 1.0.1 already fixed it? Or any other change from the WP or Easy Footnotes. My test 404 link gets reported within Footnotes. So therefore I close this.

If the error can be reproduced in some way, please re-open and add details how to reproduce the bug with a step-by-step explanation. Thanks!

**Closed as completed by Zodiac1978** 2023-04-16 15:56 UTC
Labels: bug
